services:
  - type: web
    name: reevanta-backend
    runtime: python
    plan: free
    region: singapore
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: PYTHONPATH
        value: .
      - key: MONGO_URL
        value: mongodb+srv://surajjaiswal1236_db_user:sbOryAXAZlXXk4kA@cluster0.uz8jzby.mongodb.net/reevanta_db?retryWrites=true&w=majority
      - key: DB_NAME
        value: reevanta_db
      - key: JWT_SECRET
        value: reevanta_secret_key_2026_super_secure
      - key: CORS_ORIGINS
        value: "*"
      - key: ENVIRONMENT
        value: production
      - key: NEPALOTP_API_KEY
        value: npot_live_At6UCnVKZC6JE4EQRppa1UWkYfavmBVwaFiSAPIa
      - key: IMAGEKIT_PUBLIC_KEY
        value: public_0oD+msTktt3r1xWwdVrOqlBUyDA=
      - key: IMAGEKIT_PRIVATE_KEY
        value: private_BqZaPX73d1p6Ma4xHTWIYqwZD4M=
      - key: IMAGEKIT_URL_ENDPOINT
        value: https://ik.imagekit.io/h7oalyucx

  - type: web
    name: reevanta-frontend
    runtime: node
    plan: free
    region: singapore
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://reevanta-backend-pg3v.onrender.com/api
      - key: REACT_APP_BACKEND_URL
        value: https://reevanta-backend-pg3v.onrender.com

  - type: web
    name: reevanta-admin
    runtime: node
    plan: free
    region: singapore
    rootDir: admin
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://reevanta-backend-pg3v.onrender.com/api
      - key: REACT_APP_BACKEND_URL
        value: https://reevanta-backend-pg3v.onrender.com
